services:
  - type: web
    name: t-bill
    runtime: node
    plan: free
    buildCommand: npm install --ignore-optional
    startCommand: npm run migrate && npm run seed && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: tbill-db
          property: connectionString
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

databases:
  - name: tbill-db
    plan: free
    databaseName: tbill
